version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"   # Web UI
      - "7077:7077"   # Port pour la communication Spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_IP=spark-master
    networks:
      - spark-network
    volumes:
      - spark-master-data:/bitnami

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077  # Se connecter au maître
      - SPARK_LOCAL_IP=spark-worker
    networks:
      - spark-network

  # Optionnel : ajout d'un service Jupyter Notebook pour tester PySpark
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - PYSPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  spark-master-data:
    driver: local
